#!/bin/bash
# Stage Wine into the app build (run by the IPA workflow before xcodegen):
#   - static libraries from the "Stage 2 - Wine unix side" workflow (engine/wine/out)
#   - Madeira's app-side Wine sources (bridge, iOS display driver, input) compiled in place
#   - the prebuilt Windows side: ARM64EC DLL farm, NLS tables, prefix template
# Writes Config/Wine.xcconfig and App/Generated/wine_version.h.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/engine/wine"
# shellcheck disable=SC1091
source "$HERE/PIN"
M="$HERE/madeira"
LIBS="$HERE/out"

for l in libntdll_unix libwin32u_unix libwineserver; do
    [ -s "$LIBS/$l.a" ] || { echo "missing $LIBS/$l.a (run the Wine unix workflow first)"; exit 1; }
done

# App files and resources only: no submodules needed here.
if [ ! -d "$M/.git" ] || [ "$(git -C "$M" rev-parse HEAD)" != "$MADEIRA_SHA" ]; then
    rm -rf "$M"
    git init -q "$M"
    git -C "$M" remote add origin "$MADEIRA_REPO"
    git -C "$M" fetch -q --depth 1 origin "$MADEIRA_SHA"
    git -C "$M" checkout -q FETCH_HEAD
fi
A="$M/app/Madeira"
ls "$A/arm64ec-windows/ntdll.dll" "$A/arm64ec-windows/xtajit64.dll" "$A/prefix-template.tar.gz" > /dev/null

# No-JIT step B: with MYIOSDECK_NOJIT_EMULATOR set, system32\xtajit64.dll points at the stub
# emulator (engine/pedylib/emu) instead of FEX, which needs JIT.
python3 - "$A/WineProcessBridge.m" <<'PY'
import sys
p = sys.argv[1]
s = open(p).read()
mark = "MYIOSDECK_NOJIT_EMULATOR"
anchor = 'dprintf(STDERR_FILENO, "[WineProc] Symlinked %d DLLs from %s -> sys32\\n", linked, bundle_subdir);\n'
if mark not in s:
    assert s.count(anchor) == 1, "WineProcessBridge.m anchor"
    s = s.replace(anchor, anchor + r'''            {
                const char *emu = getenv("MYIOSDECK_NOJIT_EMULATOR");
                if (emu && *emu) {
                    NSString *dst = [sys32Dir stringByAppendingPathComponent:@"xtajit64.dll"];
                    [fm removeItemAtPath:dst error:nil];
                    BOOL ok = [fm createSymbolicLinkAtPath:dst withDestinationPath:[NSString stringWithUTF8String:emu] error:nil];
                    dprintf(STDERR_FILENO, "[WineProc] no-JIT: xtajit64.dll -> %s (%s)\n", emu, ok ? "ok" : "FAILED");
                }
            }
''')
    open(p, "w").write(s)
PY

LINK=""
for f in "$LIBS"/*.a; do LINK="$LINK \$(SRCROOT)/${f#"$ROOT/"}"; done
mkdir -p "$ROOT/Config" "$ROOT/App/Generated"
cat > "$ROOT/Config/Wine.xcconfig" <<X
// Generated by engine/wine/stage-app.sh — do not edit.
MYIOSDECK_WINE_HEADERS = \$(SRCROOT)/engine/wine/madeira/app/Madeira
MYIOSDECK_WINE_LIBS = $LINK -lz -framework IOKit -framework VideoToolbox -framework CoreMedia -framework CoreVideo -framework AudioToolbox -framework AVFoundation -framework CoreHaptics -framework ImageIO -framework GameController -framework Metal -framework QuartzCore
X
cat > "$ROOT/App/Generated/wine_version.h" <<H
// Generated by engine/wine/stage-app.sh
#define MYIOSDECK_WITH_WINE 1
#define MYIOSDECK_MADEIRA_SHA "${MADEIRA_SHA}"
H
# Add the sources and resources to the XcodeGen spec (CI working copy only).
python3 - "$ROOT/project.yml" <<'PY'
import sys
p = sys.argv[1]
base = "engine/wine/madeira/app/Madeira/"
srcs = ["WineProcessBridge.m", "WineServerBridge.m", "IOSDisplayShim.m", "PadOutput.m",
        "PrefixExtractor.c", "wine_stubs.c", "Winios/Winios.m", "Winios/WiniosGamepad.c",
        "Winios/WiniosCursor.c"]
lines = [f"      - path: {base}{f}" for f in srcs]
# aarch64-windows and i386-windows: 32-bit games (WoW64, docs/NO_JIT_WOW64.md). Madeira's launch
# path takes a 32-bit target's session from the aarch64 farm and links syswow64 to the i386 farm
# (filled by build-ipa.yml from wine-i386.yml; without it, i386-windows holds only .gitkeep and
# no target is treated as 32-bit).
for d in ["arm64ec-windows", "aarch64-windows", "i386-windows", "nls"]:
    lines += [f"      - path: {base}{d}", "        type: folder", "        buildPhase: resources"]
lines += [f"      - path: {base}prefix-template.tar.gz", "        buildPhase: resources"]
s = open(p).read()
assert "# @WINE_SOURCES@" in s
s = s.replace("      # @WINE_SOURCES@", "\n".join(lines))
open(p, "w").write(s)
PY
cat "$ROOT/Config/Wine.xcconfig"
mkdir -p "$A/i386-windows"
du -sh "$A/arm64ec-windows" "$A/aarch64-windows" "$A/i386-windows" "$A/nls"
