#!/bin/bash
# Stage Wine into the app build (run by the IPA workflow before xcodegen):
#   - static libraries from the "Stage 2 - Wine unix side" workflow (engine/wine/out)
#   - Madeira's app-side Wine sources (bridge, iOS display driver, input) compiled in place
#   - the prebuilt Windows side: ARM64EC DLL farm, NLS tables, prefix template
# Writes Config/Wine.xcconfig and App/Generated/wine_version.h.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/engine/wine"
# shellcheck disable=SC1091
source "$HERE/PIN"
M="$HERE/madeira"
LIBS="$HERE/out"

for l in libntdll_unix libwin32u_unix libwineserver; do
    [ -s "$LIBS/$l.a" ] || { echo "missing $LIBS/$l.a (run the Wine unix workflow first)"; exit 1; }
done

# App files and resources only: no submodules needed here.
if [ ! -d "$M/.git" ] || [ "$(git -C "$M" rev-parse HEAD)" != "$MADEIRA_SHA" ]; then
    rm -rf "$M"
    git init -q "$M"
    git -C "$M" remote add origin "$MADEIRA_REPO"
    git -C "$M" fetch -q --depth 1 origin "$MADEIRA_SHA"
    git -C "$M" checkout -q FETCH_HEAD
fi
A="$M/app/Madeira"
ls "$A/arm64ec-windows/ntdll.dll" "$A/arm64ec-windows/xtajit64.dll" "$A/prefix-template.tar.gz" > /dev/null

LINK=""
for f in "$LIBS"/*.a; do LINK="$LINK \$(SRCROOT)/${f#"$ROOT/"}"; done
mkdir -p "$ROOT/Config" "$ROOT/App/Generated"
cat > "$ROOT/Config/Wine.xcconfig" <<X
// Generated by engine/wine/stage-app.sh — do not edit.
MYIOSDECK_WINE_HEADERS = \$(SRCROOT)/engine/wine/madeira/app/Madeira
MYIOSDECK_WINE_LIBS = $LINK -lz -framework VideoToolbox -framework CoreMedia -framework CoreVideo -framework AudioToolbox -framework AVFoundation -framework CoreHaptics -framework ImageIO -framework GameController -framework Metal -framework QuartzCore
X
cat > "$ROOT/App/Generated/wine_version.h" <<H
// Generated by engine/wine/stage-app.sh
#define MYIOSDECK_WITH_WINE 1
#define MYIOSDECK_MADEIRA_SHA "${MADEIRA_SHA}"
H
cat "$ROOT/Config/Wine.xcconfig"
du -sh "$A/arm64ec-windows" "$A/nls"
