#!/bin/bash
# Build FEXCore for iOS arm64 (macOS host with Xcode) and write the Xcode
# config that links it into the app.
#   engine/fex/build-ios.sh
# Outputs:
#   engine/fex/src/            pinned FEX checkout (headers are used by the app)
#   engine/fex/build-ios/      CMake build tree
#   Config/FEX.xcconfig        search paths + static libraries for the app target
#   App/Generated/engine_version.h
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/engine/fex"
# shellcheck disable=SC1091
source "$HERE/PIN"
SRC="$HERE/src"
# Code generation target for FEX itself. apple-a17 = iPhone 15 Pro / Pro Max (A17 Pro).
# Use apple-a15 (or "generic") for older iPhones.
TUNE_CPU="${MYIOSDECK_CPU:-apple-a17}"
B="$HERE/build-ios"

if [ ! -d "$SRC/.git" ] || [ "$(git -C "$SRC" rev-parse HEAD 2>/dev/null)" != "$SHA" ]; then
    rm -rf "$SRC"
    git init -q "$SRC"
    git -C "$SRC" remote add origin "$REPO"
    git -C "$SRC" fetch -q --depth 1 origin "$SHA"
    git -C "$SRC" checkout -q FETCH_HEAD
fi
# Only the submodules FEXCore needs (skip the large test-binary repos).
git -C "$SRC" submodule update --init --depth 1 --jobs 8 \
    External/fmt External/xxhash External/range-v3 External/unordered_dense \
    External/vixl External/drm-headers External/Vulkan-Headers External/rpmalloc \
    Source/Common/cpp-optparse

if [ ! -f "$B/CMakeCache.txt" ]; then
    cmake -S "$SRC" -B "$B" -G Ninja \
        -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_ARCHITECTURES=arm64 \
        -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_DEPLOYMENT_TARGET=17.0 -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER="$(xcrun -f clang)" -DCMAKE_CXX_COMPILER="$(xcrun -f clang++)" \
        -DBUILD_TESTING=OFF -DBUILD_THUNKS=OFF -DBUILD_FEXCONFIG=OFF -DBUILD_FEX_LINUX_TESTS=OFF \
        -DENABLE_FEX_ALLOCATOR=OFF -DENABLE_ASSERTIONS=OFF -DENABLE_CLANG_THUNKS=ON -DENABLE_CCACHE=OFF \
        -DENABLE_OFFLINE_TELEMETRY=OFF -DTUNE_CPU="$TUNE_CPU"         -DOVERRIDE_VERSION="madeira-ios-${SHA:0:10}"
fi
cmake --build "$B" --target FEXCore FEXCore_Base JemallocLibs cephes_128bit softfloat_3e fmt xxhash

LIBS=()
for name in FEXCore FEXCore_Base JemallocLibs cephes_128bit softfloat_3e fmt xxhash; do
    f="$(find "$B" -name "lib${name}.a" -print -quit)"
    [ -n "$f" ] || { echo "missing lib${name}.a" >&2; exit 1; }
    LIBS+=("$f")
done

mkdir -p "$ROOT/Config" "$ROOT/App/Generated"
{
    echo "// Generated by engine/fex/build-ios.sh — do not edit."
    echo "MYIOSDECK_FEX_HEADERS = \$(SRCROOT)/engine/fex/src/FEXCore/include \$(SRCROOT)/engine/fex/src/FEXHeaderUtils \$(SRCROOT)/engine/fex/src/CodeEmitter \$(SRCROOT)/engine/fex/src/External/fmt/include \$(SRCROOT)/engine/fex/src/External/range-v3/include \$(SRCROOT)/engine/fex/src/External/unordered_dense/include \$(SRCROOT)/engine/fex/build-ios \$(SRCROOT)/engine/fex/build-ios/include \$(SRCROOT)/engine/fex/build-ios/FEXCore/Source \$(SRCROOT)/engine/fex/src"
    printf 'MYIOSDECK_FEX_LIBS ='
    for f in "${LIBS[@]}"; do printf ' $(SRCROOT)/%s' "${f#"$ROOT/"}"; done
    echo
} > "$ROOT/Config/FEX.xcconfig"
cat > "$ROOT/App/Generated/engine_version.h" <<H
// Generated by engine/fex/build-ios.sh
#define MYIOSDECK_WITH_FEX 1
#define MYIOSDECK_FEX_SHA "${SHA}"
H
cat "$ROOT/Config/FEX.xcconfig"
ls -la "${LIBS[@]}"
