#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Build MYIOSDECK's GOG installer unpacker: innoextract (engine/innoextract/PIN, with
# myiosdeck.patch), the Boost sources it needs and myiosdeck_inno.cpp, as one static library.
#   engine/innoextract/build.sh ios          -> engine/innoextract/build-ios/libinno_ios.a,
#                                               Config/Inno.xcconfig, App/Generated/inno_version.h
#   engine/innoextract/build.sh host <dir>   -> <dir>/unpack_test (the CI test; Linux or macOS)
# Downloads go to engine/innoextract/deps (CI caches it by PIN).
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/engine/innoextract"
# shellcheck disable=SC1091
source "$HERE/PIN"
TARGET="${1:?usage: build.sh ios | host <out_dir>}"
SRC="$HERE/src"
DEPS="$HERE/deps"
mkdir -p "$DEPS"

fetch() { # dir repo commit
    if [ ! -d "$1/.git" ] || [ "$(git -C "$1" rev-parse HEAD 2>/dev/null)" != "$3" ]; then
        rm -rf "$1"
        git init -q "$1"
        git -C "$1" remote add origin "$2"
        git -C "$1" fetch -q --depth 1 origin "$3"
        git -C "$1" checkout -q FETCH_HEAD
    fi
}

fetch "$SRC" "$REPO" "$SHA"
git -C "$SRC" checkout -q -- .
git -C "$SRC" apply "$HERE/myiosdeck.patch"
fetch "$DEPS/xz" "$XZ_REPO" "$XZ_SHA"

# Boost: only the headers and the two libraries' sources are unpacked.
BOOST_NAME="$(basename "$BOOST_URL" .tar.bz2)"
BOOST="$DEPS/$BOOST_NAME"
if [ ! -f "$BOOST/.complete" ]; then
    TARBALL="$DEPS/$BOOST_NAME.tar.bz2"
    curl -fsSL --retry 3 -o "$TARBALL" "$BOOST_URL"
    echo "$BOOST_SHA256  $TARBALL" | shasum -a 256 -c -
    rm -rf "$BOOST"
    tar -xjf "$TARBALL" -C "$DEPS" "$BOOST_NAME/boost" "$BOOST_NAME/libs/filesystem/src" "$BOOST_NAME/libs/iostreams/src"
    rm -f "$TARBALL"
    touch "$BOOST/.complete"
fi

GEN=Ninja
command -v ninja > /dev/null || GEN="Unix Makefiles"
COMMON=(-DIX_SRC="$SRC" -DBOOST_SRC="$BOOST" -DLZMA_INCLUDE="$DEPS/xz/src/liblzma/api" -DINNO_SHA="$SHA"
        -DCMAKE_BUILD_TYPE=Release)

case "$TARGET" in
ios)
    OUT="$HERE/build-ios"
    cmake -S "$HERE" -B "$OUT/cmake" -G "$GEN" "${COMMON[@]}" \
        -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_SYSTEM_PROCESSOR=arm64 -DCMAKE_OSX_ARCHITECTURES=arm64 \
        -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_DEPLOYMENT_TARGET=17.0 \
        -DCMAKE_C_COMPILER="$(xcrun -f clang)" -DCMAKE_CXX_COMPILER="$(xcrun -f clang++)"
    cmake --build "$OUT/cmake" --parallel
    cp "$OUT/cmake/libmyiosdeck_inno.a" "$OUT/libinno_ios.a"
    ls -la "$OUT/libinno_ios.a"
    # Link check: everything the library needs comes from the iOS SDK's own libraries.
    SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
    xcrun --sdk iphoneos clang++ -arch arm64 -isysroot "$SDK" -miphoneos-version-min=17.0 \
        -x c -I"$ROOT/App/Sources/Native" "$HERE/test/unpack_test.c" -x none "$OUT/libinno_ios.a" \
        -lz -lbz2 -llzma -liconv -o "$OUT/unpack_test_ios"
    echo "iOS link check: ok"

    mkdir -p "$ROOT/Config" "$ROOT/App/Generated"
    cat > "$ROOT/Config/Inno.xcconfig" <<X
// Generated by engine/innoextract/build.sh — do not edit.
MYIOSDECK_INNO_LIBS = \$(SRCROOT)/engine/innoextract/build-ios/libinno_ios.a
X
    cat > "$ROOT/App/Generated/inno_version.h" <<H
// Generated by engine/innoextract/build.sh
#define MYIOSDECK_WITH_INNO 1
#define MYIOSDECK_INNO_SHA "${SHA}"
H
    ;;
host)
    OUT="$(mkdir -p "${2:?host needs an output directory}" && cd "$2" && pwd)"
    cmake -S "$HERE" -B "$OUT/cmake" -G "$GEN" "${COMMON[@]}" -DMID_INNO_TEST=ON
    cmake --build "$OUT/cmake" --parallel
    cp "$OUT/cmake/unpack_test" "$OUT/unpack_test"
    ls -la "$OUT/unpack_test"
    ;;
*)
    echo "usage: build.sh ios | host <out_dir>" >&2
    exit 2
    ;;
esac
