#!/bin/bash
# Build Blink (x86-64 interpreter, JIT disabled) as a static library for iOS
# arm64, plus MYIOSDECK's embedding driver.
#   engine/blink/build-ios.sh
# Outputs:
#   engine/blink/build-ios/libblink_ios.a
#   Config/Blink.xcconfig, App/Generated/blink_version.h
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
HERE="$ROOT/engine/blink"
# shellcheck disable=SC1091
source "$HERE/PIN"
SRC="$HERE/src"
OUT="$HERE/build-ios"
OBJ="$OUT/obj"

if [ ! -d "$SRC/.git" ] || [ "$(git -C "$SRC" rev-parse HEAD 2>/dev/null)" != "$SHA" ]; then
    rm -rf "$SRC"
    git init -q "$SRC"
    git -C "$SRC" remote add origin "$REPO"
    git -C "$SRC" fetch -q --depth 1 origin "$SHA"
    git -C "$SRC" checkout -q FETCH_HEAD
fi

# configure probes the host (macOS arm64, the same kernel family and libc as
# iOS); the sources are then compiled with the iOS SDK. No JIT: iOS without a
# debugger cannot make memory executable, which is the whole point of this path.
cd "$SRC"
CC=clang ./configure --disable-jit --disable-fork --disable-overlays --disable-vfs \
    --disable-strace --disable-metal --disable-sockets --disable-rom
# The probe ran on macOS; drop what iOS lacks (no <sys/random.h>, no clock_settime).
sed -i '' -e 's|^#define HAVE_SYS_GETENTROPY|// #define HAVE_SYS_GETENTROPY|'           -e 's|^#define HAVE_GETENTROPY|// #define HAVE_GETENTROPY|'           -e 's|^#define HAVE_CLOCK_SETTIME|// #define HAVE_CLOCK_SETTIME|' config.h
grep -E '^#define' config.h

SDK="$(xcrun --sdk iphoneos --show-sdk-path)"
CLANG="$(xcrun --sdk iphoneos -f clang)"
CFLAGS=(-arch arm64 -isysroot "$SDK" -miphoneos-version-min=17.0 -O2 -g0
        -fno-stack-protector -fomit-frame-pointer -fno-strict-aliasing -fwrapv
        -D_DARWIN_C_SOURCE -DNDEBUG -iquote "$SRC" -I"$SRC"
        '-DBLINK_COMMITS=\"0\"' '-DBLINK_UNAME_V=\"ios\"'
        -include "$HERE/ios_overrides.h" -Wno-unused-command-line-argument)
rm -rf "$OBJ" && mkdir -p "$OBJ" "$OUT"

printf '%s\n' "${CFLAGS[@]}" > "$OUT/cflags.rsp"
for f in "$SRC"/blink/*.c; do
    case "$(basename "$f")" in blink.c|blinkenlights.c|oneoff.c) continue ;; esac
    echo "$f"
done > "$OUT/sources.txt"
# Parallel compile in batches of 8 (works with macOS's bash 3.2); every failure
# is printed so one log shows all of them.
FAIL=0
i=0
while read -r f; do
    (
        n="$(basename "$f" .c)"
        "$CLANG" @"$OUT/cflags.rsp" -c "$f" -o "$OBJ/$n.o" 2> "$OBJ/$n.err" ||
            { echo "FAILED $f"; cat "$OBJ/$n.err"; touch "$OBJ/$n.failed"; }
    ) &
    i=$((i + 1))
    [ $((i % 8)) -ne 0 ] || wait
done < "$OUT/sources.txt"
wait
if ls "$OBJ"/*.failed > /dev/null 2>&1; then FAIL=1; fi
"$CLANG" @"$OUT/cflags.rsp" -I"$ROOT/App/Sources/Native" -DMYIOSDECK_BLINK_SHA="\"$SHA\"" -c "$HERE/myiosdeck_driver.c" -o "$OBJ/myiosdeck_driver.o" || FAIL=1
[ "$FAIL" = 0 ] || { echo "Blink: some files failed to compile"; exit 1; }

rm -f "$OUT/libblink_ios.a"
xcrun --sdk iphoneos ar rcs "$OUT/libblink_ios.a" "$OBJ"/*.o
ls -la "$OUT/libblink_ios.a"

mkdir -p "$ROOT/Config" "$ROOT/App/Generated"
cat > "$ROOT/Config/Blink.xcconfig" <<X
// Generated by engine/blink/build-ios.sh — do not edit.
MYIOSDECK_BLINK_LIBS = \$(SRCROOT)/engine/blink/build-ios/libblink_ios.a
X
cat > "$ROOT/App/Generated/blink_version.h" <<H
// Generated by engine/blink/build-ios.sh
#define MYIOSDECK_WITH_BLINK 1
#define MYIOSDECK_BLINK_SHA "${SHA}"
H
